spring:
  profiles:
    active: dev
  application:
    name: fin-tracker

server:
  port: 8080
  servlet:
    context-path: /

app:
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437 # Placeholder secret key for JWT
    expiration-ms: 86400000 # 24 hours

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Actuator configuration for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,prometheus
  endpoint:
    health:
      show-details: when_authorized
    loggers:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true