spring:
  profiles:
    active: dev
  application:
    name: fin-tracker
  config:
    import: classpath:secrets.yml

server:
  port: 8080
  servlet:
    context-path: /

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Actuator configuration for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,prometheus
  endpoint:
    health:
      show-details: when_authorized
    loggers:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Security configuration is externalized to secrets.yml
# Add a secrets.yml file in the same directory as application.yml
# It needs to contain the following:
# app:
#   jwt:
#     # This is a secure JWT secret key generated for server-side use only
#     secret: <32 characters long random string>
#     expiration-ms: 86400000 # 24 hours
