spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fintracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.fintracker: INFO
    org.springframework: WARN
    org.hibernate: WARN
  config: classpath:logback/logback-spring.xml